apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: team-a
spec:
  containers:
  - name: nginx
    image: nginx:latest
  - name: busybox
    image: docker.io/busybox:1.36
  initContainers:
  - name: init
    image: gcr.io/google-samples/hello-app:1.0
